name: Build and Release PDF

on:
  push:
    tags:
      - 'v*.*.*'  # Se activa solo en tags de versión (ej. v1.0.0)

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/islandoftex/images/texlive:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build PDF
        run: |
          cd guia  
          make

      - name: Find PDF
        run: |
          mkdir -p output_pdfs
          find guia -type f -name "*.pdf" -exec cp {} output_pdfs/ \;
        shell: bash

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-pdf
          path: output_pdfs/*.pdf


  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download PDF Artifact
        uses: actions/download-artifact@v4
        with:
          name: built-pdf
          path: downloaded_pdfs  # Descarga todos los PDFs en este directorio
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: downloaded_pdfs/C-basica.pdf
          generate_release_notes: true
